
app:
  name: taizhou
  port: 8080

redis:
  host: 127.0.0.1
  port: 6379
  password: root
  expire: 300
  maxIdle: 2
  maxActive: 5

db:
  driver: mysql
  host: 127.0.0.1
  port: 3306
  name: taizhou_ir
  user: root
  password: root

upload:
  path: uploads
  ext: .jpg|.jpeg|.png

jwt:
    secret: my2secVerifyPKCS1v1sdsa5retkey